// Generated by Selenium IDE

namespace my_diary_tests;

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using my_diary_tests;

[TestFixture]
public class LogoutTest : TestBase
{
  [Test, Order(4)]
  public void Logout()
  {
    appManager.Navigation.OpenHomePage();
    appManager.Authentication.Login(appManager.authentication.userData);
    appManager.Authentication.Logout();
    appManager.Stop();
  }
}
