// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using my_diary_tests;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace my_diary_tests;

[TestFixture]
public class CreateNoteTest : AuthBase {
  
  public NoteData notedata = new NoteData("the header", 
    "Нам всем кажется, что если — не скрою, и мне иногда так " +
    "кажется — что если навести твёрдый порядок жёсткой рукой, " +
    "то всем нам станет жить лучше, комфортнее и безопаснее. На самом деле, эта «комфортность» очень быстро пройдёт, потому что эта жёсткая рука начнёт нас очень быстро душить.");

  
  [Test, Order(2)]
  public void СreateNote() {
    int count = appManager.Posting.GetNotesInfo();
    appManager.Posting.CreateNote(notedata);
    Assert.AreEqual(count+1,appManager.Posting.GetNotesInfo());
    appManager.Stop();
  }
}
