// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using my_diary_tests;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace my_diary_tests;

[TestFixture]
public class DeleteNoteTest : AuthBase {
    [Test, Order(3)]
    public void DeleteNote()
    {
      int count = appManager.Posting.GetNotesInfo() - 1;
      Thread.Sleep(1000);
      appManager.Posting.DeleteNote();
      Assert.AreEqual(count,  appManager.Posting.GetNotesInfo());
    }
}
