// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using my_diary_tests;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace my_diary_tests;


[TestFixture]
public class DeleteNoteTest : TestBase {
  
  public NoteData notedata = new NoteData("note to delete", 
    "Нам всем кажется, что если — не скрою, и мне иногда так " +
    "кажется — что если навести твёрдый порядок жёсткой рукой, " +
    "то всем нам станет жить лучше, комфортнее и безопаснее. " +
    "На самом деле, эта «комфортность» очень быстро пройдёт, " +
    "потому что эта жёсткая рука начнёт нас очень быстро душить.");

  [Test, Order(3)]
  public void DeleteNote()
  {
    appManager.Navigation.OpenHomePage();
    appManager.Authentication.Login(appManager.authentication.userData);
    int count = appManager.Posting.GetNotesInfo() - 1;
    Thread.Sleep(1000);
    appManager.Posting.DeleteNote();
    Assert.AreEqual(count,  appManager.Posting.GetNotesInfo());
  }
}
