// Generated by Selenium IDE

using System.Diagnostics;

namespace my_diary_tests;

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using my_diary_tests;

using System.Xml.Serialization;
using System.Xml.Serialization;
using my_diary_tests;


[TestFixture]
public class DeserializeTest : AuthBase
{
    public static IEnumerable<NoteData> NoteFromXmlFile()
     {
         return (List<NoteData>) new XmlSerializer(typeof(List<NoteData>))
             .Deserialize(new FileStream(@"C:\Users\Владислава\RiderProjects\my-diary-tests\my-diary-tests\text.xml", FileMode.OpenOrCreate));
     }

     [Test, TestCaseSource("NoteFromXmlFile")]
     public void CreateNoteFromXMLTest(NoteData noteData)
     {
         
         int count = appManager.Posting.GetNotesInfo();
         appManager.Posting.CreateNote(noteData);
         Assert.AreEqual(count+1,appManager.Posting.GetNotesInfo());
     }
     

}
