// Generated by Selenium IDE

namespace my_diary_tests;

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using my_diary_tests;

[TestFixture]
public class LogouttestTest : TestBase
{
  public AccountData userData = new AccountData("vladislava.turina@yandex.ru", "q2eueq0vl");

  [Test, Order(4)]
  public void LogoutTest()
  {
    appManager.Navigation.OpenHomePage();
    appManager.Authentication.Login(userData);
    appManager.Authentication.Logout();
    //Assert.AreEqual(true, appManager.loggedIn);
  }
}
